title: ["ArcadeVS"]
description: ["Description"]
marketplaceURL: ["https://www.unrealengine.com/marketplace/en-US/store"]

remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
    "PoyoWorks on github":
      - "//github.com/poyoworks"
