title: ["ArcadeVS"]
description: ["Description"]
marketplaceURL: ["https://www.unrealengine.com/marketplace/en-US/arcade-vehicle-system"]
pcdemoURL: ["https://drive.google.com/open?id=1WaeAxBaCbi7nJhmofw-PHJz3Z1ywfvlL"]

remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
    "PoyoWorks on github":
      - "//github.com/poyoworks"
